// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Working from "./Working.res.js";
import * as NotWorking from "./NotWorking.res.js";

var NotWorking$1 = NotWorking.make;

var Working$1 = Working.make;

var Workaround = NotWorking.make;

export {
  NotWorking$1 as NotWorking,
  Working$1 as Working,
  Workaround ,
}
/* Working Not a pure module */
