// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function make(param) {
  return JsxRuntime.jsx("div", {
              children: param.children
            });
}

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
